### ISSUE TITLE
Invalid size representation "24px!important

### ISSUE THREAD

**Issue by jaypeeperos** [Dinamiko/dk-pdf#91]
Got this error on our site:

PHP Fatal error: Uncaught Mpdf\\MpdfException: Invalid size representation "24px!important" in /nas/content/live/manualofideas1/wp-content/plugins/dk-pdf/vendor/mpdf/mpdf/src/SizeConverter.php:35\nStack trace:\n#0 /nas/content/live/manualofideas1/wp-content/plugins/dk-pdf/vendor/mpdf/mpdf/src/Mpdf.php(19570): Mpdf\\SizeConverter->convert('24px!important', 3.52777777778)\n#1 /nas/content/live/manualofideas1/wp-content/plugins/dk-pdf/vendor/mpdf/mpdf/src/Tag/A.php(36): Mpdf\\Mpdf->setCSS(Array, 'INLINE')\n#2 /nas/content/live/manualofideas1/wp-content/plugins/dk-pdf/vendor/mpdf/mpdf/src/Tag.php(239): Mpdf\\Tag\\A->open(Array, Array, 285)\n#3 /nas/content/live/manualofideas1/wp-content/plugins/dk-pdf/vendor/mpdf/mpdf/src/Mpdf.php(15310): Mpdf\\Tag->OpenTag('A', Array, Array, 285)\n#4 /nas/content/live/manualofideas1/wp-content/plugins/dk-pdf/includes/dkpdf-functions.php(198): Mpdf\\Mpdf->WriteHTML(' <div class="dk...')\n#5 /nas/content/live/manualofideas1/wp-includes/class-wp-hook.php(307): dkpdf_output_pdf(Object(WP))\n#6 /nas/content/live/ma in /nas/content/live/manualofideas1/wp-content/plugins/dk-pdf/vendor/mpdf/mpdf/src/SizeConverter.php on line 35, referer: https://moiglobal.com/global-fashion-group-gfg-2022/

**Comment by Dinamiko** [comment]
We are closing this issue due to inactivity. You can reopen or create a new issue at any time if you're still experiencing this problem.
